fix for broken build
usbfatfs example does not build: undefined reference to 'sceUsbd*'
missing reference to deal with usb (the entire initialization): just call it fixes building, since linker can find references